import {defineType, defineField} from 'sanity'

export default defineType({
  name: 'uiStrings',
  title: 'UI Strings',
  type: 'document',
  description: 'Common text, labels, and microcopy used across the entire site',
  groups: [
    {name: 'navigation', title: 'Navigation'},
    {name: 'buttons', title: 'Common Buttons'},
    {name: 'forms', title: 'Form Labels'},
    {name: 'messages', title: 'Messages & Alerts'},
    {name: 'footer', title: 'Footer'},
    {name: 'dates', title: 'Date & Time'},
  ],
  fields: [
    // Navigation
    defineField({
      name: 'navVacationRentals',
      title: 'Vacation Rentals',
      type: 'string',
      group: 'navigation',
      initialValue: 'Vacation Rentals',
    }),
    defineField({
      name: 'navIslandGuide',
      title: 'Island Guide',
      type: 'string',
      group: 'navigation',
      initialValue: 'Island Guide',
    }),
    defineField({
      name: 'navMarketplace',
      title: 'Marketplace',
      type: 'string',
      group: 'navigation',
      initialValue: 'Marketplace',
    }),
    defineField({
      name: 'navShop',
      title: 'Shop',
      type: 'string',
      group: 'navigation',
      initialValue: 'Shop',
    }),
    defineField({
      name: 'navSpecials',
      title: 'Specials',
      type: 'string',
      group: 'navigation',
      initialValue: 'Specials',
    }),
    defineField({
      name: 'navPropertyManagement',
      title: 'Property Management',
      type: 'string',
      group: 'navigation',
      initialValue: 'Property Management',
    }),
    defineField({
      name: 'navOwnerLogin',
      title: 'Owner Login',
      type: 'string',
      group: 'navigation',
      initialValue: 'Owner Login',
    }),
    defineField({
      name: 'navAbout',
      title: 'About',
      type: 'string',
      group: 'navigation',
      initialValue: 'About',
    }),
    defineField({
      name: 'navContact',
      title: 'Contact',
      type: 'string',
      group: 'navigation',
      initialValue: 'Contact',
    }),
    defineField({
      name: 'navSignIn',
      title: 'Sign In',
      type: 'string',
      group: 'navigation',
      initialValue: 'Sign In',
    }),
    defineField({
      name: 'navRegister',
      title: 'Register',
      type: 'string',
      group: 'navigation',
      initialValue: 'Register',
    }),
    defineField({
      name: 'navMyAccount',
      title: 'My Account',
      type: 'string',
      group: 'navigation',
      initialValue: 'My Account',
    }),
    defineField({
      name: 'navFavorites',
      title: 'Favorites',
      type: 'string',
      group: 'navigation',
      initialValue: 'Favorites',
    }),
    defineField({
      name: 'navSearch',
      title: 'Search',
      type: 'string',
      group: 'navigation',
      initialValue: 'Search',
    }),

    // Common Buttons
    defineField({
      name: 'btnLearnMore',
      title: 'Learn More',
      type: 'string',
      group: 'buttons',
      initialValue: 'Learn More',
    }),
    defineField({
      name: 'btnViewAll',
      title: 'View All',
      type: 'string',
      group: 'buttons',
      initialValue: 'View All',
    }),
    defineField({
      name: 'btnViewDetails',
      title: 'View Details',
      type: 'string',
      group: 'buttons',
      initialValue: 'View Details',
    }),
    defineField({
      name: 'btnSubmit',
      title: 'Submit',
      type: 'string',
      group: 'buttons',
      initialValue: 'Submit',
    }),
    defineField({
      name: 'btnCancel',
      title: 'Cancel',
      type: 'string',
      group: 'buttons',
      initialValue: 'Cancel',
    }),
    defineField({
      name: 'btnClose',
      title: 'Close',
      type: 'string',
      group: 'buttons',
      initialValue: 'Close',
    }),
    defineField({
      name: 'btnSave',
      title: 'Save',
      type: 'string',
      group: 'buttons',
      initialValue: 'Save',
    }),
    defineField({
      name: 'btnShare',
      title: 'Share',
      type: 'string',
      group: 'buttons',
      initialValue: 'Share',
    }),
    defineField({
      name: 'btnCopyLink',
      title: 'Copy Link',
      type: 'string',
      group: 'buttons',
      initialValue: 'Copy Link',
    }),
    defineField({
      name: 'btnBackToTop',
      title: 'Back to Top',
      type: 'string',
      group: 'buttons',
      initialValue: 'Back to Top',
    }),

    // Form Labels
    defineField({
      name: 'formName',
      title: 'Name Field',
      type: 'string',
      group: 'forms',
      initialValue: 'Name',
    }),
    defineField({
      name: 'formEmail',
      title: 'Email Field',
      type: 'string',
      group: 'forms',
      initialValue: 'Email',
    }),
    defineField({
      name: 'formPhone',
      title: 'Phone Field',
      type: 'string',
      group: 'forms',
      initialValue: 'Phone',
    }),
    defineField({
      name: 'formMessage',
      title: 'Message Field',
      type: 'string',
      group: 'forms',
      initialValue: 'Message',
    }),
    defineField({
      name: 'formRequired',
      title: 'Required Indicator',
      type: 'string',
      group: 'forms',
      initialValue: 'Required',
    }),
    defineField({
      name: 'formOptional',
      title: 'Optional Indicator',
      type: 'string',
      group: 'forms',
      initialValue: 'Optional',
    }),

    // Messages
    defineField({
      name: 'msgSuccess',
      title: 'Success Message',
      type: 'string',
      group: 'messages',
      initialValue: 'Success!',
    }),
    defineField({
      name: 'msgError',
      title: 'Error Message',
      type: 'string',
      group: 'messages',
      initialValue: 'Something went wrong. Please try again.',
    }),
    defineField({
      name: 'msgLoading',
      title: 'Loading Message',
      type: 'string',
      group: 'messages',
      initialValue: 'Loading...',
    }),
    defineField({
      name: 'msgNoResults',
      title: 'No Results Message',
      type: 'string',
      group: 'messages',
      initialValue: 'No results found.',
    }),
    defineField({
      name: 'msgAddedToFavorites',
      title: 'Added to Favorites',
      type: 'string',
      group: 'messages',
      initialValue: 'Added to favorites',
    }),
    defineField({
      name: 'msgRemovedFromFavorites',
      title: 'Removed from Favorites',
      type: 'string',
      group: 'messages',
      initialValue: 'Removed from favorites',
    }),
    defineField({
      name: 'msgLinkCopied',
      title: 'Link Copied',
      type: 'string',
      group: 'messages',
      initialValue: 'Link copied to clipboard',
    }),

    // Footer
    defineField({
      name: 'footerTagline',
      title: 'Footer Tagline',
      type: 'string',
      group: 'footer',
      initialValue: 'Your Hatteras Island vacation starts here.',
    }),
    defineField({
      name: 'footerQuickLinks',
      title: 'Quick Links Heading',
      type: 'string',
      group: 'footer',
      initialValue: 'Quick Links',
    }),
    defineField({
      name: 'footerVillages',
      title: 'Villages Heading',
      type: 'string',
      group: 'footer',
      initialValue: 'Villages',
    }),
    defineField({
      name: 'footerSupport',
      title: 'Support Heading',
      type: 'string',
      group: 'footer',
      initialValue: 'Support',
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Copyright Text',
      type: 'string',
      group: 'footer',
      initialValue: '© {year} Surf or Sound Realty. All rights reserved.',
      description: 'Use {year} as placeholder for current year',
    }),

    // Date/Time
    defineField({
      name: 'dateArrival',
      title: 'Arrival',
      type: 'string',
      group: 'dates',
      initialValue: 'Arrival',
    }),
    defineField({
      name: 'dateDeparture',
      title: 'Departure',
      type: 'string',
      group: 'dates',
      initialValue: 'Departure',
    }),
    defineField({
      name: 'dateNights',
      title: 'Nights',
      type: 'string',
      group: 'dates',
      initialValue: 'nights',
    }),
    defineField({
      name: 'dateSelectDates',
      title: 'Select Dates',
      type: 'string',
      group: 'dates',
      initialValue: 'Select dates',
    }),
  ],
  preview: {
    prepare() {
      return {
        title: 'UI Strings',
        subtitle: 'Common text across the site',
      }
    },
  },
})
