/**
 * Mock Property Data
 *
 * Real-looking property data with Unsplash images for development
 * These images are from Unsplash's free API and are safe to use
 */

import type { Property } from '@/types';

// Beach house images from Unsplash (free to use)
const beachImages = {
  oceanfront1: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&q=80',
  oceanfront2: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
  oceanfront3: 'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=800&q=80',
  oceanfront4: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
  beachHouse1: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
  beachHouse2: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&q=80',
  beachHouse3: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
  beachHouse4: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
  beachHouse5: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
  beachHouse6: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
  cottage1: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&q=80',
  cottage2: 'https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?w=800&q=80',
  luxury1: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
  luxury2: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
  family1: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
  family2: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80',
  pool1: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
  pool2: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
  interior1: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&q=80',
  interior2: 'https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800&q=80',
};

// Helper to create village object with required id
const createVillage = (name: string, slug: string) => ({
  id: slug,
  name,
  slug,
});

export const featuredProperties: Property[] = [
  {
    id: 'prop-1',
    trackId: '1001',
    name: 'Oceanfront Paradise',
    slug: 'oceanfront-paradise-1001',
    headline: 'Wake up to stunning ocean views from this luxurious beachfront retreat',
    bedrooms: 5,
    bathrooms: 4.5,
    sleeps: 12,
    propertyType: 'House',
    village: createVillage('Avon', 'avon'),
    petFriendly: true,
    featured: true,
    baseRate: 3500,
    amenities: [],
    images: [
      { url: beachImages.oceanfront1, alt: 'Oceanfront Paradise exterior' },
      { url: beachImages.interior1, alt: 'Living room' },
      { url: beachImages.pool1, alt: 'Private pool' },
    ],
  },
  {
    id: 'prop-2',
    trackId: '1002',
    name: 'Sunset Retreat',
    slug: 'sunset-retreat-1002',
    headline: 'Perfect family getaway with private pool and soundside dock',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    propertyType: 'House',
    village: createVillage('Buxton', 'buxton'),
    petFriendly: false,
    featured: true,
    baseRate: 2800,
    amenities: [],
    images: [
      { url: beachImages.beachHouse1, alt: 'Sunset Retreat exterior' },
      { url: beachImages.interior2, alt: 'Kitchen' },
    ],
  },
  {
    id: 'prop-3',
    trackId: '1003',
    name: 'Lighthouse View',
    slug: 'lighthouse-view-1003',
    headline: 'Historic charm meets modern comfort with views of Cape Hatteras Lighthouse',
    bedrooms: 6,
    bathrooms: 5,
    sleeps: 14,
    propertyType: 'House',
    village: createVillage('Buxton', 'buxton'),
    petFriendly: true,
    featured: true,
    baseRate: 4200,
    amenities: [],
    images: [
      { url: beachImages.luxury1, alt: 'Lighthouse View exterior' },
      { url: beachImages.pool2, alt: 'Pool area' },
    ],
  },
  {
    id: 'prop-4',
    trackId: '1004',
    name: 'Waves Wonder',
    slug: 'waves-wonder-1004',
    headline: 'Cozy beach cottage steps from the sand in quiet Waves village',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    propertyType: 'Cottage',
    village: createVillage('Waves', 'waves'),
    petFriendly: true,
    featured: true,
    baseRate: 1800,
    amenities: [],
    images: [
      { url: beachImages.cottage1, alt: 'Waves Wonder exterior' },
      { url: beachImages.beachHouse3, alt: 'Beach view' },
    ],
  },
  {
    id: 'prop-5',
    trackId: '1005',
    name: 'Dolphin Dreams',
    slug: 'dolphin-dreams-1005',
    headline: 'Watch dolphins play from your private deck on this soundside gem',
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 10,
    propertyType: 'House',
    village: createVillage('Salvo', 'salvo'),
    petFriendly: false,
    featured: true,
    baseRate: 2400,
    amenities: [],
    images: [
      { url: beachImages.beachHouse2, alt: 'Dolphin Dreams exterior' },
      { url: beachImages.oceanfront2, alt: 'Ocean view' },
    ],
  },
];

export const trendingProperties: Property[] = [
  {
    id: 'prop-6',
    trackId: '1006',
    name: 'Kite Rider\'s Haven',
    slug: 'kite-riders-haven-1006',
    headline: 'Prime location for kiteboarding enthusiasts in Rodanthe',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    propertyType: 'House',
    village: createVillage('Rodanthe', 'rodanthe'),
    petFriendly: true,
    featured: false,
    baseRate: 2200,
    amenities: [],
    images: [
      { url: beachImages.oceanfront3, alt: 'Kite Rider\'s Haven' },
      { url: beachImages.beachHouse4, alt: 'Beach access' },
    ],
  },
  {
    id: 'prop-7',
    trackId: '1007',
    name: 'Fisherman\'s Cove',
    slug: 'fishermans-cove-1007',
    headline: 'Steps from Hatteras Harbor - perfect for fishing enthusiasts',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    propertyType: 'Cottage',
    village: createVillage('Hatteras Village', 'hatteras-village'),
    petFriendly: true,
    featured: false,
    baseRate: 1600,
    amenities: [],
    images: [
      { url: beachImages.cottage2, alt: 'Fisherman\'s Cove' },
      { url: beachImages.beachHouse5, alt: 'Deck' },
    ],
  },
  {
    id: 'prop-8',
    trackId: '1008',
    name: 'Sandcastle Manor',
    slug: 'sandcastle-manor-1008',
    headline: 'Grand oceanfront estate perfect for family reunions',
    bedrooms: 8,
    bathrooms: 7,
    sleeps: 20,
    propertyType: 'House',
    village: createVillage('Avon', 'avon'),
    petFriendly: false,
    featured: false,
    baseRate: 5800,
    amenities: [],
    images: [
      { url: beachImages.luxury2, alt: 'Sandcastle Manor' },
      { url: beachImages.pool1, alt: 'Pool' },
    ],
  },
  {
    id: 'prop-9',
    trackId: '1009',
    name: 'Seabreeze Cottage',
    slug: 'seabreeze-cottage-1009',
    headline: 'Charming renovated cottage with vintage Outer Banks character',
    bedrooms: 2,
    bathrooms: 1,
    sleeps: 6,
    propertyType: 'Cottage',
    village: createVillage('Frisco', 'frisco'),
    petFriendly: true,
    featured: false,
    baseRate: 1200,
    amenities: [],
    images: [
      { url: beachImages.beachHouse6, alt: 'Seabreeze Cottage' },
      { url: beachImages.interior1, alt: 'Interior' },
    ],
  },
  {
    id: 'prop-10',
    trackId: '1010',
    name: 'Captain\'s Quarters',
    slug: 'captains-quarters-1010',
    headline: 'Nautical-themed home with private hot tub and game room',
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 12,
    propertyType: 'House',
    village: createVillage('Salvo', 'salvo'),
    petFriendly: false,
    featured: false,
    baseRate: 3200,
    amenities: [],
    images: [
      { url: beachImages.oceanfront4, alt: 'Captain\'s Quarters' },
      { url: beachImages.interior2, alt: 'Game room' },
    ],
  },
];

export const staffPickProperties: Property[] = [
  {
    id: 'prop-11',
    trackId: '1011',
    name: 'Hidden Gem',
    slug: 'hidden-gem-1011',
    headline: 'Our team\'s favorite - quiet location with stunning sunsets',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    village: { name: 'Frisco', slug: 'frisco' },
    petFriendly: true,
    featured: false,
    baseRate: 2100,
    images: [
      { url: beachImages.beachHouse3, alt: 'Hidden Gem exterior' },
      { url: beachImages.pool2, alt: 'Pool area' },
    ],
  },
  {
    id: 'prop-12',
    trackId: '1012',
    name: 'The Islander',
    slug: 'the-islander-1012',
    headline: 'Best value on the island - recently renovated with ocean views',
    bedrooms: 3,
    bathrooms: 2,
    sleeps: 8,
    village: { name: 'Waves', slug: 'waves' },
    petFriendly: false,
    featured: false,
    baseRate: 1500,
    images: [
      { url: beachImages.family1, alt: 'The Islander' },
      { url: beachImages.interior1, alt: 'Living room' },
    ],
  },
  {
    id: 'prop-13',
    trackId: '1013',
    name: 'Avon Oasis',
    slug: 'avon-oasis-1013',
    headline: 'Walk to restaurants and shops from this central Avon location',
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 12,
    village: { name: 'Avon', slug: 'avon' },
    petFriendly: true,
    featured: false,
    baseRate: 2900,
    images: [
      { url: beachImages.beachHouse4, alt: 'Avon Oasis' },
      { url: beachImages.oceanfront2, alt: 'Ocean view' },
    ],
  },
  {
    id: 'prop-14',
    trackId: '1014',
    name: 'Pelican Point',
    slug: 'pelican-point-1014',
    headline: 'Watch pelicans dive from your private pier on the sound',
    bedrooms: 4,
    bathrooms: 3.5,
    sleeps: 10,
    village: { name: 'Rodanthe', slug: 'rodanthe' },
    petFriendly: false,
    featured: false,
    baseRate: 2600,
    images: [
      { url: beachImages.luxury1, alt: 'Pelican Point' },
      { url: beachImages.beachHouse5, alt: 'Soundside' },
    ],
  },
  {
    id: 'prop-15',
    trackId: '1015',
    name: 'Surfside Inn',
    slug: 'surfside-inn-1015',
    headline: 'Classic beach house with wrap-around porches and ocean breezes',
    bedrooms: 6,
    bathrooms: 5,
    sleeps: 14,
    village: { name: 'Buxton', slug: 'buxton' },
    petFriendly: true,
    featured: false,
    baseRate: 3800,
    images: [
      { url: beachImages.oceanfront1, alt: 'Surfside Inn' },
      { url: beachImages.pool1, alt: 'Pool' },
    ],
  },
];

export const familyFriendlyProperties: Property[] = [
  {
    id: 'prop-16',
    trackId: '1016',
    name: 'Family Fun House',
    slug: 'family-fun-house-1016',
    headline: 'Game room, pool, and private beach access - kids love it!',
    bedrooms: 6,
    bathrooms: 5,
    sleeps: 16,
    village: { name: 'Avon', slug: 'avon' },
    petFriendly: true,
    featured: false,
    baseRate: 4500,
    images: [
      { url: beachImages.family2, alt: 'Family Fun House' },
      { url: beachImages.pool2, alt: 'Pool' },
    ],
  },
  {
    id: 'prop-17',
    trackId: '1017',
    name: 'Sandy Toes Retreat',
    slug: 'sandy-toes-retreat-1017',
    headline: 'Fenced yard, outdoor shower, and short walk to the beach',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    village: { name: 'Salvo', slug: 'salvo' },
    petFriendly: true,
    featured: false,
    baseRate: 2300,
    images: [
      { url: beachImages.family1, alt: 'Sandy Toes Retreat' },
      { url: beachImages.beachHouse6, alt: 'Backyard' },
    ],
  },
  {
    id: 'prop-18',
    trackId: '1018',
    name: 'Beachcomber\'s Delight',
    slug: 'beachcombers-delight-1018',
    headline: 'Kids\' bunk room, video games, and steps to the sand',
    bedrooms: 5,
    bathrooms: 4,
    sleeps: 14,
    village: { name: 'Waves', slug: 'waves' },
    petFriendly: false,
    featured: false,
    baseRate: 2800,
    images: [
      { url: beachImages.beachHouse2, alt: 'Beachcomber\'s Delight' },
      { url: beachImages.interior2, alt: 'Kids room' },
    ],
  },
  {
    id: 'prop-19',
    trackId: '1019',
    name: 'Turtle Tracks',
    slug: 'turtle-tracks-1019',
    headline: 'Watch sea turtles nest from this quiet oceanfront home',
    bedrooms: 4,
    bathrooms: 3,
    sleeps: 10,
    village: { name: 'Frisco', slug: 'frisco' },
    petFriendly: true,
    featured: false,
    baseRate: 2700,
    images: [
      { url: beachImages.oceanfront3, alt: 'Turtle Tracks' },
      { url: beachImages.beachHouse3, alt: 'Beach' },
    ],
  },
  {
    id: 'prop-20',
    trackId: '1020',
    name: 'Lighthouse Landing',
    slug: 'lighthouse-landing-1020',
    headline: 'Walk to the lighthouse and enjoy the best of Buxton',
    bedrooms: 5,
    bathrooms: 4.5,
    sleeps: 12,
    village: { name: 'Buxton', slug: 'buxton' },
    petFriendly: false,
    featured: false,
    baseRate: 3400,
    images: [
      { url: beachImages.luxury2, alt: 'Lighthouse Landing' },
      { url: beachImages.pool1, alt: 'Pool' },
    ],
  },
];

// Get all properties
export function getAllMockProperties(): Property[] {
  return [
    ...featuredProperties,
    ...trendingProperties,
    ...staffPickProperties,
    ...familyFriendlyProperties,
  ];
}
